"""Schemas for AI alert analysis.

Two models, deliberately separate:

- `LLMAnalysisOutput` is the *untrusted* contract the model must satisfy. It is
  strict: scores must be real integers in 0-100 (no "85", 85.5 or `true`),
  classification must be one of three labels, unknown fields are rejected, and
  every string/list is length-bounded.
- `AnalysisResult` is what the engine returns to callers. Its citations are
  rebuilt from the chunks that were actually retrieved (the model can't invent
  sources), and it carries server-side safety metadata the model does not
  control: validation warnings, human-review flags, and provenance.
"""
from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StringConstraints, field_validator


class Classification(StrEnum):
    benign = "Benign"
    suspicious = "Suspicious"
    malicious = "Malicious"


Score = Annotated[StrictInt, Field(ge=0, le=100)]
ShortText = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=1000)]
ChunkRef = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=200)]


class LLMAnalysisOutput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    classification: Classification
    risk_score: Score
    confidence_score: Score
    reasoning: Annotated[
        str, StringConstraints(strip_whitespace=True, min_length=1, max_length=6000)
    ]
    recommended_action: Annotated[
        str, StringConstraints(strip_whitespace=True, min_length=1, max_length=3000)
    ]
    evidence: list[ShortText] = Field(min_length=1, max_length=25)
    unsupported_claims: list[ShortText] = Field(default_factory=list, max_length=25)
    retrieved_knowledge: list[ChunkRef] = Field(default_factory=list, max_length=20)

    @field_validator("classification", mode="before")
    @classmethod
    def normalise_label(cls, v: object) -> object:
        # Tolerate case/whitespace only ("malicious " -> "Malicious"); any other
        # label (e.g. "Critical", "Unknown") still fails enum validation.
        if isinstance(v, str):
            return v.strip().capitalize()
        return v


class KnowledgeReference(BaseModel):
    """A knowledge chunk the model cited, verified against what was retrieved."""

    chunk_id: str
    title: str
    category: str
    source: str
    score: float


ADVISORY_NOTICE = (
    "Advisory output only. This assessment was generated by an AI model and must be "
    "reviewed by a human analyst. It does not authorise or trigger any containment, "
    "blocking, deletion, or account action."
)


class AnalysisResult(BaseModel):
    alert_id: str
    classification: Classification
    risk_score: int = Field(ge=0, le=100)
    confidence_score: int = Field(ge=0, le=100)
    reasoning: str
    recommended_action: str
    evidence: list[str]
    unsupported_claims: list[str]
    retrieved_knowledge: list[KnowledgeReference]

    # --- server-side metadata (not model-controlled) ---
    knowledge_sufficient: bool
    human_review_required: bool
    human_review_reasons: list[str]
    validation_warnings: list[str]
    advisory_notice: str = ADVISORY_NOTICE
    provider: str
    model: str
    prompt_version: str
    attempts: int
    latency_ms: int
