"""FastAPI application entrypoint.

Uses an application factory so tests can build a fresh app with overridden
settings and dependency overrides.

Startup (lifespan) prepares the database, optionally seeds the dataset when the
table is empty, and optionally warms the RAG index. Seeding and warming are
best-effort: a failure is logged and the API still starts, so an operator can
reach `/health/ready` and see exactly what is missing rather than facing a
container that crash-loops.
"""
from __future__ import annotations

import logging
import re
import time
import uuid
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from app.api.alerts import router as alerts_router
from app.api.analyze import router as analyze_router
from app.api.deps import build_rag_service
from app.api.errors import register_exception_handlers
from app.api.health import router as health_router
from app.api.rag import router as rag_router
from app.core.config import get_settings
from app.core.logging import configure_logging, request_id_var
from app.db import initialize_database, make_engine, make_session_factory
from app.repositories import AlertRepository

logger = logging.getLogger(__name__)

_REQUEST_ID_RE = re.compile(r"^[A-Za-z0-9._-]{1,64}$")


class _RequestTooLarge(Exception):
    """Raised from the ASGI receive wrapper when a body exceeds the limit."""


def _too_large(limit: int) -> JSONResponse:
    logger.warning("Rejected request body over %d bytes", limit)
    return JSONResponse(
        status_code=413,
        content={"error": {
            "code": "payload_too_large",
            "message": f"Request body exceeds the {limit} byte limit.",
            "request_id": request_id_var.get(),
            "details": None,
        }},
    )

DESCRIPTION = """
RAG-grounded triage assistant for SOC security alerts.

Given an alert, the service retrieves relevant internal security knowledge and
asks an LLM for a structured assessment: classification, risk score, confidence,
reasoning, evidence and a recommended next step.

**The output is advisory.** It is generated by an AI model, is validated and
guardrailed server-side, and must be reviewed by a human analyst. The service
never isolates a host, blocks an address, disables an account or deletes a file.
"""

TAGS_METADATA = [
    {"name": "analysis", "description": "Analyse an alert with RAG + LLM (advisory only)."},
    {"name": "alerts", "description": "Browse dataset alerts and their stored assessments."},
    {"name": "rag", "description": "Knowledge base maintenance."},
    {"name": "health", "description": "Liveness and readiness."},
]


def _seed_if_empty(session_factory) -> None:
    from app.seed import seed

    settings = get_settings()
    with session_factory() as session:
        count = AlertRepository(session).count()
    if count:
        logger.info("Startup: %d alerts already present, skipping seed.", count)
        return
    total = seed(database_url=settings.database_url)
    logger.info("Startup: seeded %d alerts from the dataset.", total)


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    settings = get_settings()

    db_engine = make_engine(settings.database_url)
    try:
        migration_result = initialize_database(db_engine)
        if migration_result.applied:
            logger.info("Startup: applied migrations %s", migration_result.applied)
    except Exception as exc:
        # Unwritable path, bad URL, DB down: keep serving so /health works and
        # data endpoints answer 503 instead of the container crash-looping.
        logger.error(
            "Startup: database initialisation failed (%s)", type(exc).__name__, exc_info=exc
        )
    app.state.db_engine = db_engine
    app.state.session_factory = make_session_factory(db_engine)
    app.state.rag_service = None
    app.state.analysis_engine = None

    if settings.auto_seed:
        try:
            _seed_if_empty(app.state.session_factory)
        except Exception as exc:  # dataset missing/invalid: log and keep serving
            logger.error("Startup: dataset seeding failed (%s)", type(exc).__name__, exc_info=exc)

    if settings.rag_warm_on_startup:
        try:
            app.state.rag_service = build_rag_service(settings)
            logger.info("Startup: RAG index warm.")
        except Exception as exc:
            logger.error("Startup: RAG warm-up failed (%s)", type(exc).__name__, exc_info=exc)

    logger.info(
        "Ready: %s (env=%s, llm_configured=%s, provider=%s, model=%s)",
        settings.app_name, settings.environment, settings.llm_configured,
        settings.llm_provider, settings.llm_model,
    )
    yield
    db_engine.dispose()


def create_app() -> FastAPI:
    configure_logging()
    settings = get_settings()

    # Interactive docs describe every endpoint and schema to an unauthenticated
    # caller; off by default in production (ENABLE_API_DOCS overrides).
    docs = settings.docs_enabled
    app = FastAPI(
        title=settings.app_name,
        version="1.0.0",
        description=DESCRIPTION,
        openapi_tags=TAGS_METADATA,
        lifespan=lifespan,
        docs_url="/docs" if docs else None,
        redoc_url="/redoc" if docs else None,
        openapi_url="/openapi.json" if docs else None,
    )
    if not docs:
        logger.info("API docs disabled (environment=%s).", settings.environment)

    origins = settings.cors_origin_list
    if "*" in origins:
        # Allowed, but never silently: with no auth layer this lets any site
        # call the API from a visitor's browser.
        logger.warning("CORS is configured to allow any origin ('*').")
    app.add_middleware(
        CORSMiddleware,
        allow_origins=origins,
        # Never true while origins may be "*", and there is no cookie/session
        # auth to carry anyway.
        allow_credentials=False,
        allow_methods=["GET", "POST"],
        allow_headers=["Content-Type", "X-Request-ID"],
        expose_headers=["X-Request-ID"],
        max_age=600,
    )

    @app.middleware("http")
    async def limit_request_size(request: Request, call_next):
        """Reject oversized bodies before they are buffered or parsed.

        The declared Content-Length is checked first (cheap), then the actual
        stream is counted, so a chunked request cannot lie about its size.
        """
        limit = settings.max_request_bytes
        declared = request.headers.get("content-length")
        if declared and declared.isdigit() and int(declared) > limit:
            return _too_large(limit)

        received = 0
        stream = request.receive

        async def counting_receive():
            nonlocal received
            message = await stream()
            if message["type"] == "http.request":
                received += len(message.get("body", b""))
                if received > limit:
                    raise _RequestTooLarge
            return message

        request._receive = counting_receive  # noqa: SLF001 - ASGI has no public hook
        try:
            return await call_next(request)
        except _RequestTooLarge:
            return _too_large(limit)

    @app.middleware("http")
    async def request_context(request: Request, call_next):
        """Tag each request with an id (echoed in logs, the error envelope and
        the `X-Request-ID` header) and log its outcome."""
        incoming = request.headers.get("x-request-id", "")
        request_id = incoming if _REQUEST_ID_RE.match(incoming) else uuid.uuid4().hex[:16]
        token = request_id_var.set(request_id)
        started = time.monotonic()
        try:
            response = await call_next(request)
        finally:
            duration_ms = int((time.monotonic() - started) * 1000)
            request_id_var.reset(token)
        response.headers["X-Request-ID"] = request_id
        # Health probes are frequent and uninteresting at INFO.
        level = logging.DEBUG if request.url.path.startswith("/health") else logging.INFO
        logger.log(
            level, "%s %s -> %d (%dms)",
            request.method, request.url.path, response.status_code, duration_ms,
            extra={"method": request.method, "path": request.url.path,
                   "status_code": response.status_code, "duration_ms": duration_ms,
                   "request_id": request_id},
        )
        return response

    register_exception_handlers(app)

    app.include_router(health_router)
    app.include_router(alerts_router)
    app.include_router(analyze_router)
    app.include_router(rag_router)

    return app


app = create_app()
